version: '3'

services:

  ntopng:
    image: liujinbao3000/ntopng
    command: --community -d /var/lib/ntopng -i eth0 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
    volumes:
      - /var/local/docker/ntopng/ntopng:/var/lib/ntopng
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: --save 900 1
    ports:
      - "6379:6379"
    volumes:
      - /var/local/docker/ntopng/redis:/data
    restart: unless-stopped
